config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user

  validates :title, :url, :description, :user_id,  presence: true
  validates :title, length: { maximum: 100 }
  validates :url, length: { maximum: 200 }
  validates :description, length: { maximum: 255 }
  validates :url, format_url: true

  scope :newest, ->{ order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :users

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  before_save { self.email = email.to_s.downcase }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include MoviesHelper
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.newest.page(params[:page]).per 5
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @movie.user = current_user

    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :url, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash[:danger] = 'Invalid email/password combination'
      redirect_to root_path
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Funny Movies"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def display_video(url)
    url_id = YouTubeRails.extract_video_id(url) || url
    "https://www.youtube.com/embed/#{url_id}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to root_path, id: "logo" do %>
      <span class="glyphicon glyphicon-home"></span>
      Funny Movies
    <% end %>

    <div class="user-action">
      <% if logged_in? %>
        <div class="logout-form">
          <span>
            Welcome
            <%= link_to current_user.email, user_path(current_user) %>
          </span>
          <%= button_tag(type: :button) do %>
            <% link_to "Share a movie", new_movie_path, class: "black-text" %>
          <% end %>
          <%= button_tag(type: :button) do %>
            <% link_to "Logout", logout_path, method: :delete, class: "black-text" %>
          <% end %>
        </div>
      <% else %>
        <%= form_for :session, url: login_path, html: {class: "login-form"} do |f| %>
          <%= f.email_field :email, placeholder: "email" %>
          <%= f.password_field :password, placeholder: "password" %>
          <%= f.submit "Log in", class: "" %>
          <%= button_tag(type: :button) do %>
            <%= link_to "Register", new_user_path, class: "black-text" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= form_with model: movie, local: true do |form| %>
      <% if movie.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

          <ul>
          <% movie.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label :url %>
        <%= form.text_field :url, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", rows: 8 %>
      </div>

      <div class="actions">
        <% button_name = form.object.new_record? ? "Share" : "Update" %>
        <%= form.submit button_name, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-3">
      <iframe src="<%= display_video movie.url %>" class="w-100" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
      </iframe>
    </div>
    <div class="col-md-5">
      <p>
        <%= link_to movie_path(movie), class: "red-text" do %>
          <%= movie.title %>
        <% end %>
      </p>
      <p>Shared by: <%= movie.user.email %></p>
      <p>Description:</p>
      <p>
        <strong>
          <%= truncate movie.description, length: 100, omission: "... (continued)" %>
        </strong>
      </p>
    </div>
    <div class="col-md-2"></div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-9">
    <%= paginate @movies %>
  </div>
</div>

app/views/movies/new.html.erb
<h1>Share a movie</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-3">
    <iframe src="<%= display_video @movie.url %>" class="w-100" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
    </iframe>
  </div>
  <div class="col-md-5">
    <p class="red-text">
      <%= @movie.title %>
    </p>
    <p>Description:</p>
    <p><strong><%= @movie.description %></strong></p>
    <% if current_user&.id == @movie.user_id %>
      <p>
        <%= link_to "Edit", edit_movie_path(@movie), class: "btn btn-primary" %>
        <%= link_to "Delete", movie_path(@movie), method: :delete, class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= form_with(model: user, local: true) do |form| %>
      <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>

      <div class="actions">
        <% button_name = form.object.new_record? ? "Create" : "Update" %>
        <%= form.submit button_name, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render "form", user: @user %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to edit_user_path(@user) do %>
  <button class="btn btn-primary">Edit</button>
<% end %>